### ISSUE TITLE
Problem building libsghostty

### ISSUE THREAD

**Issue by igorkulman** [supabitapp/supacode#386]
libghostty does not seem to build with zig 0.15.2 on macOS 26.5.1 with Xcode 26.5, looks like this problem https://codeberg.org/ziglang/zig/issues/31658 fixed in Zig 0.16.0 but using Zig 0.16.0 fails else where

```
src/build/zig.zig:13:9: error: Your Zig version v0.16.0 does not meet the required build version of v0.15.2
```

What is the recommended setup to make the problem build with latest macOS and Xcode?

**Comment by sbertix** [comment]
Yeah, we're still using Xcode 26.3 because of that. 
Let me see if we can finally move away from it 💪

**Comment by sbertix** [comment]
Covered by the `make doctor` and the updated `REAMDE` in #468
